# Generated by Django 5.0.2 on 2024-10-23 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام برند')),
                ('nationality', models.CharField(max_length=100, verbose_name='ملیت برند')),
            ],
            options={
                'verbose_name': 'برند',
                'verbose_name_plural': 'برند ها',
            },
        ),
        migrations.CreateModel(
            name='mobile_phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, unique=True, verbose_name='مدل گوشی')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت')),
                ('color', models.CharField(max_length=50, verbose_name='رنگ')),
                ('screen_size', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='سایز صفحه نمایش')),
                ('status', models.CharField(choices=[('available', 'Available'), ('not_available', 'Not Available')], max_length=20, verbose_name='وضعیت')),
                ('manufacturer_country', models.CharField(max_length=100, verbose_name='کشور سازنده')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.brand', verbose_name='برند')),
            ],
            options={
                'verbose_name': 'موبایل',
                'verbose_name_plural': 'موبایل ها',
            },
        ),
    ]
